name: Automated NPM CalVer version bump
description: GitHub Action for automated CalVer version bumps for NPM.
runs:
  using: docker
  image: Dockerfile
branding:
  icon: calendar
  color: blue
inputs:
  tag-prefix:
    description: 'Git tag prefix'
    default: ''
    required: false
  skip-tag:
    description: 'Skip Git tagging'
    default: 'false'
    required: false
  PACKAGEJSON_DIR:
    description: 'Custom package.json location'
    default: ''
    required: false
  target-branch:
    description: 'Target branch for version bump'
    default: ''
    required: false
  commit-message:
    description: 'Custom git commit message'
    default: ''
    required: false
outputs:
  newTag:
    description: 'Bumped version tag'
